library(shiny)
library(dplyr)
library(ggplot2)
library(data.table)
library(tidyr)
library(gganimate)
library(leaflet)
library(geojsonio)
library(maps)
library(htmlwidgets)
library(htmltools)
library(rgdal)
library(zoo)
flights <- fread(file = "flights14.csv")
data=read.csv("./infectious_disease_predictability/Data/INFLUENZA_Cases_1919-1951_20151014132002.csv",stringsAsFactors=FALSE)
data[data=='-']<-0
data[]<-lapply(data, function(x){as.numeric(x)})
data<-select(data, -c("AMERICAN.SAMOA", "NORTHERN.MARIANA.ISLANDS", "GUAM","PAC.TRUST.TERR","NEW.YORK.CITY","UPSTATE.NEW.YORK", "VIRGIN.ISLANDS" ))
dummy<-select(data, "PUERTO.RICO" )
data<-select(data, -"PUERTO.RICO") %>% mutate(., "PUERTO.RICO"=dummy[,])
data$WEEK<-sprintf("%02d", data$WEEK )
data<-data%>%mutate(., "TIME"=as.Date(paste(YEAR,WEEK,1,sep="" ), '%Y%U%u'))
data$TIME=na.locf(data$TIME)
x=select(data, -c("YEAR","WEEK"))

